#!/bin/sh -ex

a2dissite 000-default

# remove tomcat sslcert gen inithook (not required when Tomcat proxied by Apache)
rm -rf /usr/lib/inithooks/firstboot.d/16tomcat-sslcert

# configure tkl-webcp
WEBAPPS=/var/lib/tomcat8/webapps/
WEBROOT=$WEBAPPS/cp
mv $WEBAPPS/ROOT $WEBROOT

rm $WEBROOT/index.html

for dir in js css images; do
    mkdir -p $WEBROOT/$dir
    cp -a /var/www/$dir/* $WEBROOT/$dir
    rm -rf /var/www/$dir
done

sed -i "s|HOSTNAME_DESC|Tomcat Apache|g" $WEBROOT/index.jsp
sed -i "s|HOSTNAME|tomcat-apache|g" $WEBROOT/index.jsp
